import fs from "node:fs";
import path from "node:path";
import { apiRequest } from "../apiClient";
import { resolveEnvironment } from "../environment";
import { parseProjectEnvFlags } from "../flags";
import { requireSession } from "../session";
import { SecretMetadata, SecretWithValue } from "../types";

export async function runPull(args: string[]): Promise<void> {
  const { projectId, environmentId, out } = parseProjectEnvFlags(args);
  const credentials = requireSession();
  await resolveEnvironment(credentials, projectId, environmentId);

  const secrets = await apiRequest<SecretMetadata[]>(
    credentials.token,
    credentials.apiUrl,
    `/environments/${environmentId}/secrets`
  );

  const revealed: { key: string; value: string }[] = [];
  for (const secret of secrets) {
    const result = await apiRequest<SecretWithValue>(
      credentials.token,
      credentials.apiUrl,
      `/secrets/${secret.id}/reveal`
    );
    revealed.push({ key: secret.key, value: result.value });
  }

  revealed.sort((a, b) => a.key.localeCompare(b.key));

  const outPath = path.resolve(out ?? ".env");
  const lines = [
    "# Generated by EnvSync CLI",
    ...revealed.map((s) => `${s.key}=${s.value}`),
  ];

  fs.writeFileSync(outPath, lines.join("\n") + "\n");
  console.log(`Pulled ${revealed.length} secret(s) into ${outPath}`);
}
